let data = [
    {
        color: 'purple',
        type: 'BWE',
        number: 1,
        value: 180.22,
        hexagon: 4,
        capitalInvertido: 1600.00,
        retorno: 7.0,
        drawdown: -37.0,
        score: 78.2
    },
    {
        color: 'orange',
        type: 'NTI',
        number: 2,
        value: 99.22,
        hexagon: 6,
        capitalInvertido: 160.00,
        retorno: 4.0,
        drawdown: 39.0,
        score: 98.2
    },
    {
        color: 'yellow',
        type: 'BWE',
        number: 3,
        value: 100.22,
        hexagon: 8,
        capitalInvertido: 50.00,
        retorno: 60.0,
        drawdown: 10.0,
        score: 2.2
    },
    {
        color: 'purple',
        type: 'BWE',
        number: 4,
        value: 200.22,
        hexagon: 5,
        capitalInvertido: 89.00,
        retorno: 32.0,
        drawdown: 23.0,
        score: 45.2
    },
    {
        color: 'orange',
        type: 'NTI',
        number: 5,
        value: 99.22,
        hexagon: 6,
        capitalInvertido: 160.00,
        retorno: 4.0,
        drawdown: 39.0,
        score: 98.2
    },
    {
        color: 'yellow',
        type: 'NTI',
        number: 6,
        value: 100.22,
        hexagon: 8,
        capitalInvertido: 50.00,
        retorno: 60.0,
        drawdown: 10.0,
        score: 2.2
    },
    {
        color: 'purple',
        type: 'BWE',
        number: 7,
        value: 180.22,
        hexagon: 4,
        capitalInvertido: 1600.00,
        retorno: 7.0,
        drawdown: -37.0,
        score: 78.2
    },
    {
        color: 'orange',
        type: 'NTI',
        number: 8,
        value: 99.22,
        hexagon: 6,
        capitalInvertido: 160.00,
        retorno: 4.0,
        drawdown: 39.0,
        score: 98.2
    },
    {
        color: 'yellow',
        type: 'BWE',
        number: 9,
        value: 100.22,
        hexagon: 8,
        capitalInvertido: 50.00,
        retorno: 60.0,
        drawdown: 10.0,
        score: 2.2
    },
    {
        color: 'purple',
        type: 'BWE',
        number: 10,
        value: 200.22,
        hexagon: 5,
        capitalInvertido: 89.00,
        retorno: 32.0,
        drawdown: 23.0,
        score: 45.2
    },
    {
        color: 'orange',
        type: 'NTI',
        number: 11,
        value: 99.22,
        hexagon: 6,
        capitalInvertido: 160.00,
        retorno: 4.0,
        drawdown: 39.0,
        score: 98.2
    },
    {
        color: 'yellow',
        type: 'NTI',
        number: 12,
        value: 100.22,
        hexagon: 8,
        capitalInvertido: 50.00,
        retorno: 60.0,
        drawdown: 10.0,
        score: 2.2
    },
    {
        color: 'purple',
        type: 'BWE',
        number: 13,
        value: 180.22,
        hexagon: 4,
        capitalInvertido: 1600.00,
        retorno: 7.0,
        drawdown: -37.0,
        score: 78.2
    },
    {
        color: 'orange',
        type: 'NTI',
        number: 14,
        value: 99.22,
        hexagon: 6,
        capitalInvertido: 160.00,
        retorno: 4.0,
        drawdown: 39.0,
        score: 98.2
    },
    {
        color: 'yellow',
        type: 'BWE',
        number: 15,
        value: 100.22,
        hexagon: 8,
        capitalInvertido: 50.00,
        retorno: 60.0,
        drawdown: 10.0,
        score: 2.2
    },
    {
        color: 'purple',
        type: 'BWE',
        number: 16,
        value: 200.22,
        hexagon: 5,
        capitalInvertido: 89.00,
        retorno: 32.0,
        drawdown: 23.0,
        score: 45.2
    },
    {
        color: 'orange',
        type: 'NTI',
        number: 17,
        value: 99.22,
        hexagon: 6,
        capitalInvertido: 160.00,
        retorno: 4.0,
        drawdown: 39.0,
        score: 98.2
    },
    {
        color: 'yellow',
        type: 'NTI',
        number: 18,
        value: 100.22,
        hexagon: 8,
        capitalInvertido: 50.00,
        retorno: 60.0,
        drawdown: 10.0,
        score: 2.2
    },
    {
        color: 'purple',
        type: 'BWE',
        number: 19,
        value: 180.22,
        hexagon: 4,
        capitalInvertido: 1600.00,
        retorno: 7.0,
        drawdown: -37.0,
        score: 78.2
    },
    {
        color: 'orange',
        type: 'NTI',
        number: 20,
        value: 99.22,
        hexagon: 6,
        capitalInvertido: 160.00,
        retorno: 4.0,
        drawdown: 39.0,
        score: 98.2
    },
    {
        color: 'yellow',
        type: 'BWE',
        number: 21,
        value: 100.22,
        hexagon: 8,
        capitalInvertido: 50.00,
        retorno: 60.0,
        drawdown: 10.0,
        score: 2.2
    },
    {
        color: 'purple',
        type: 'BWE',
        number: 22,
        value: 200.22,
        hexagon: 5,
        capitalInvertido: 89.00,
        retorno: 32.0,
        drawdown: 23.0,
        score: 45.2
    },
    {
        color: 'orange',
        type: 'NTI',
        number: 23,
        value: 99.22,
        hexagon: 6,
        capitalInvertido: 160.00,
        retorno: 4.0,
        drawdown: 39.0,
        score: 98.2
    },
    {
        color: 'yellow',
        type: 'NTI',
        number: 24,
        value: 100.22,
        hexagon: 8,
        capitalInvertido: 50.00,
        retorno: 60.0,
        drawdown: 10.0,
        score: 2.2
    },
]

export default data;